import './globals.css'
import type { Metadata } from 'next'
import { ConfigProvider } from 'antd'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: '#6e2a2b',
              borderRadius: 8,
      
              // Alias Token
              colorBgContainer: '#ffffff',
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  )
}
